CC=gcc
CCC=g++
LD=ld

V
COMMONFLAGS = -O3 -D KHUFU_VERSION=\"$(VERSION)\" -I src
CCLAGS = $(COMMONFLAGS)-std=c++26
CFLAGS = $(COMMONFLAGS)
LIBS = -ltiff -ljpeg -lz -lzstd 
LDFLAGS =

all:  khufu

clean:
	rm -rf khufu *.o

khufu: khufu.o  mongoose.o
	$(LD) $(LDLAGS) khufu.o mongoose.o -o khufu $(LIBS)
	
khufu.o: src/khufu.cpp
	$(CCC) $(CCFLAGS) src/khufu.cpp -c -o khufu.o 

mongoose.o: src/mongoose.c
	$(CC) $(CFLAGS) src/mongoose.c -c -o mongoose.o